### ISSUE TITLE
Ordered map creation issue 

### ISSUE THREAD

**Issue by thhave** [aerospike/aerospike-client-csharp#141]
Hello,

I am unable to create a string-keyed ordered map bin with more than 10 elements using the `Put` method.
I have tried different client versions (6.2.1, 7.4.0, 8.0.0, and so on).

```CSharp
// File: MapOrderTest.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using Aerospike.Client;
using Ductus.FluentDocker;
using Ductus.FluentDocker.Services;
using Ductus.FluentDocker.Services.Extensions;
using FluentAssertions;

namespace AerospikeIssueDemo;

[TestFixture]
public class MapOrderTest
{
    private const string AerospikeImage = "aerospike:ce-6.4.0.7_2"; // "aerospike:ce-7.2.0.4_1";

    private const string Address = "127.0.0.1";

    private const int Port = 3000;

    private const string Namespace = "test";

    private const string Set = "mapordertest";

    private const int ContainerWaitingTimeout = 30000;

    private IContainerService _container;

    private AsyncClient _client;

    [OneTimeSetUp]
    public async Task SetUpAsync()
    {
        _container = Fd
                     .UseContainer()
                     .WithName("aerospike-test-server")
                     .ReuseIfExists()
                     .UseImage(AerospikeImage)
                     .ExposePort(Port, Port)
                     .Build()
                     .Start()
                     .WaitForPort($"{Port}/tcp", ContainerWaitingTimeout, Address)
                     .WaitForMessageInLogs("service ready: soon there will be cake!", ContainerWaitingTimeout);

        var configuration = _container.GetConfiguration(true);

        configuration.State.Running.Should().BeTrue();

        await Task.Delay(5000);

        _client = new AsyncClient(Address, Port);
    }

    [TestCase(10, MapOrder.UNORDERED)]
    [TestCase(100, MapOrder.UNORDERED)]
    [TestCase(1000, MapOrder.UNORDERED)]
    [TestCase(10000, MapOrder.UNORDERED)]
    [TestCase(10, MapOrder.KEY_ORDERED)]
    [TestCase(9, MapOrder.KEY_ORDERED)]
    [TestCase(100, MapOrder.KEY_ORDERED)]
    [TestCase(1000, MapOrder.KEY_ORDERED)]
    [TestCase(10000, MapOrder.KEY_ORDERED)]
    public async Task CreateAndReadMap(int itemCount, MapOrder mapOrder)
    {
        var ct = TestContext.CurrentContext.CancellationToken;

        var key = new Key(Namespace, Set, Guid.NewGuid().ToString());

        var dictionary = Enumerable.Range(0, itemCount)
                                   .ToDictionary(
                                       x => $"key_{x}",
                                       x => new Dictionary<string, object>
                                       {
                                           ["Value"] = $"Some Test Value #{x}"
                                       }
                                   );
        var bins = new Bin[]
        {
            new("Dictionary", dictionary, mapOrder)
        };

        var writePolicy = new WritePolicy
        {
            recordExistsAction = RecordExistsAction.CREATE_ONLY
        };

        await _client.Invoking(c => c.Put(writePolicy, ct, key, bins)).Should().NotThrowAsync();

        var record = (await _client.Invoking(c => c.Get(null, ct, key)).Should().NotThrowAsync()).Subject;

        record.Should().NotBeNull();
        record.bins.Should().ContainKey("Dictionary");
        record.bins["Dictionary"].Should().BeEquivalentTo(dictionary);
    }

    [OneTimeTearDown]
    public void TearDown()
    {
        _client?.Dispose();
        _container?.Dispose();
    }
}

```

```XML
<!-- File: AerospikeIssueDemo.csproj -->

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aerospike.Client" Version="7.4.0"/>
        <PackageReference Include="Ductus.FluentDocker" Version="2.10.59"/>
        <PackageReference Include="FluentAssertions" Version="7.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="NUnit" Version="4.2.2"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.4.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>

```

I encountered an error with <b>aerospike:ce-6.4.0.7_2</b>:

```
Aerospike.Client.AerospikeException: Error 4,1,30000,1000,0,BB9020011AC4202 127.0.0.1 3000: Parameter error
   at Aerospike.Client.AsyncWrite.ParseResult()
   at Aerospike.Client.AsyncSingleCommand.ParseCommand()
   at Aerospike.Client.AsyncCommand.ReceiveComplete()
   at Aerospike.Client.AsyncConnectionArgs.ReceiveEvent(SocketAsyncEventArgs args)
   at Aerospike.Client.AsyncConnectionArgs.Receive()
   at Aerospike.Client.AsyncConnectionArgs.Receive(Byte[] buffer, Int32 offset, Int32 count)
   at Aerospike.Client.AsyncCommand.ReceiveComplete()
   at Aerospike.Client.AsyncConnectionArgs.ReceiveEvent(SocketAsyncEventArgs args)
   at Aerospike.Client.AsyncConnectionArgs.AsyncCompleted(Object sender, SocketAsyncEventArgs args)

```
And with <b>aerospike:ce-7.2.0.4_1</b>:

```
Aerospike.Client.AerospikeException: Error 1,1,30000,1000,0,BB9020011AC4202 127.0.0.1 3000: Server error
   at Aerospike.Client.AsyncWrite.ParseResult()
   at Aerospike.Client.AsyncSingleCommand.ParseCommand()
   at Aerospike.Client.AsyncCommand.ReceiveComplete()
   at Aerospike.Client.AsyncConnectionArgs.ReceiveEvent(SocketAsyncEventArgs args)
   at Aerospike.Client.AsyncConnectionArgs.Receive()
   at Aerospike.Client.AsyncConnectionArgs.Receive(Byte[] buffer, Int32 offset, Int32 count)
   at Aerospike.Client.AsyncCommand.ReceiveComplete()
   at Aerospike.Client.AsyncConnectionArgs.ReceiveEvent(SocketAsyncEventArgs args)
   at Aerospike.Client.AsyncConnectionArgs.AsyncCompleted(Object sender, SocketAsyncEventArgs args)

```

It works if we use integer-keyed maps.

**Comment by shannonklaus** [comment]
You need to use a `SortedDictionary` instead of `Dictionary` for your `KEY_ORDERED` bins.
This is happening specifically with `KEY_ORDERED` maps with string-keyed maps above 10 elements in your code because the server wants string-keyed maps to be sorted/ordered by each byte in the string (ie key_10 to come before key_2). We have some documentation here about ordering in maps: https://aerospike.com/docs/server/guide/data-types/cdt-ordering#string

**Comment by thhave** [comment]
Ok, Thanks
