### ISSUE TITLE
 Bin name length greater than 14 characters or maximum bins exceeded error!

### ISSUE THREAD

**Issue by doantranthanh** [aerospike/aerospike-client-csharp#39]
Hi all,

I have cloned the github. Use Aerospike docker image to setup the Aerospike server. Try to run the demo but it throw the following exception
```
2018-11-19 15:54:10 INFO Put: namespace=test set=demoset key=batchkey1 bin=batchbin value=batchvalue1
2018-11-19 15:54:10 ERROR Error 21 from BB9020011AC4202 ::1 3000: Bin name length greater than 14 characters or maximum bins exceeded
   at Aerospike.Client.WriteCommand.ParseResult(Connection conn) in C:\dev\aerospike-client-csharp\Framework\AerospikeClient\Command\WriteCommand.cs:line 50
   at Aerospike.Client.SyncCommand.Execute(Cluster cluster, Policy policy, Key key, Node node, Boolean isRead) in C:\dev\aerospike-client-csharp\Framework\AerospikeClient\Command\SyncCommand.cs:line 115
   at Aerospike.Client.AerospikeClient.Put(WritePolicy policy, Key key, Bin[] bins) in C:\dev\aerospike-client-csharp\Framework\AerospikeClient\Main\AerospikeClient.cs:line 274
   at Aerospike.Demo.Batch.WriteRecords(AerospikeClient client, Arguments args, String keyPrefix, String binName, String valuePrefix, Int32 size) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\Batch.cs:line 78
   at Aerospike.Demo.Batch.RunExample(AerospikeClient client, Arguments args) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\Batch.cs:line 39
   at Aerospike.Demo.SyncExample.RunExample(Arguments args) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\SyncExample.cs:line 45
   at Aerospike.Demo.Example.Run(Arguments args) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\Example.cs:line 44
   at Aerospike.Demo.ExampleTreeNode.Run(Arguments args) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\DemoForm.cs:line 689
   at Aerospike.Demo.DemoForm.RunExampleThread(Object data) in C:\dev\aerospike-client-csharp\Framework\AerospikeDemo\DemoForm.cs:line 370
```
so if I change the bin name from "batchbin" to "mybin" then it works. I have no idea why!

I am using Windows10, Aerospike docker image and .NET core 2.1 and .NET framwork 4.6.7!

Any ideas?

Many thanks

**Comment by mtendjou** [comment]
Just for potential future reference: https://discuss.aerospike.com/t/bin-name-wondering-why-we-have-the-limitations-of-maximum-14-characters-of-any-single-byte-double-byte-characters-are-not-allowed-for-bin-names/514/18
