### ISSUE TITLE
AsyncConnection is incompatible with MacOS

### ISSUE THREAD

**Issue by akovalov-playtika** [aerospike/aerospike-client-csharp#40]
AsyncConnection sets 
`this.socket.SendBufferSize = 0;
 this.socket.ReceiveBufferSize = 0;` in constructor.
This value is illegal for MacOS. See https://github.com/dotnet/corefx/issues/16716

`Aerospike.Client.AerospikeException+Connection: Error -8,4,BB9020011AC4202 127.0.0.1 3000: Invalid argument ---> System.Net.Sockets.SocketException: Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_SendBufferSize(Int32 value)
   at Aerospike.Client.AsyncConnection..ctor(IPEndPoint address, AsyncCluster cluster, AsyncNode node)
   --- End of inner exception stack trace ---
   at Aerospike.Client.AsyncConnection..ctor(IPEndPoint address, AsyncCluster cluster, AsyncNode node)
   at Aerospike.Client.AsyncCommand.ExecuteCommand()
`

**Comment by BrianNichols** [comment]
Thanks for bringing this to our attention.  In the next release, the C# client will only zero Send/Receive buffer sizes when the platform is not MacOS.

**Comment by BrianNichols** [comment]
Fixed in C# client 3.8.0:

https://www.aerospike.com/download/client/csharp/3.8.0/
